### ISSUE TITLE
Scraper throws on non-integer item stats

### ISSUE THREAD

**Issue by YvesW** [runelite/runelite-wiki-scraper#21]
Items such as the seers ring have a 0.2% magic bonus damage now, or 0.5% for the imbued variant. As discovered by Alex, the scraper throws on non-integer values https://github.com/runelite/runelite-wiki-scraper/blob/cf4b6238a3e5f9a69ee1bddb5c3440faa3851355/items.py#L69C1-L76C63

**Comment by abextm** [comment]
Closing in favor of runelite/runelite#18168
